### ISSUE TITLE
Have you actually tried this out with socket activation?

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/rhel-push-plugin#2]
Does it handle the first request properly?  Does the systemd unit file work without socket activation?

**Comment by runcom** [comment]
yes, let me retry this, but this is the same code base as the novolume plugin so it should work

**Comment by rhatdan** [comment]
I am just worried about either working.  Since you are supposed to be handling a leaked file descriptor into the service which the service is supposed to use.  I am concerned about docker plugins code handling this properly.  I would love to get to the point where these plugins would shut down when inactive for a certain period of time, like 1 minute.

**Comment by runcom** [comment]
> I am concerned about docker plugins code handling this properly.

I already implemented this upstream and the novolume plugins works just fine when the service is down and the socket is activated

> would love to get to the point where these plugins would shut down when inactive for a certain period of time, like 1 minute.

I'll look into this..

**Comment by runcom** [comment]
plugins already do socket activation, closing
