### ISSUE TITLE
Doesn't work when using docker over TCP socket

### ISSUE THREAD

**Issue by jasinner** [projectatomic/rhel-push-plugin#9]
If using Docker over a TCP socket (-H option on daemon) this plugin throws an error when trying to push an image.

> Error response from daemon: plugin rhel-push-plugin failed with error: AuthZPlugin.AuthZReq: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by runcom** [comment]
You need to edit the systemd unit to launch the plugin with `-host` https://github.com/projectatomic/rhel-push-plugin/blob/master/main.go#L16 and specify the remote address, then restart both plugin and docker and it works
